apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: queue
  name: queue
  namespace: moodys
spec:
  replicas: 3
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: nginx
        name: nginx
